baseURL = "https://yugsnoyl.com/"
languageCode = "en-us"
title = "yug snoyl"
theme = "pickles"

[outputs]
   home = ["html", "json", "rss"]
   posts = ["html", "json"]
   page = ["html", "json"]

[params]
    github = "guylyons"
    linkedin = "guylyons"
    twitter = "yugsnoyl"
    author = "Guy Lyons"
    avatar = "/profile.png"
    contact = "mailto:website.guy@mailhero.io"
    subtitle = "always a beginner"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about"
    weight = 3
[[menu.main]]
    name = "Illustration"
    url = "/illustration"
    weight = 2