baseURL = "https://yugsnoyl.com/"
languageCode = "en-us"
title = "Guy Lyons - Developer"
theme = "noncomplex"
# pygmentsUseClassic = true

[outputs]
   home = ["html", "json", "rss"]
   posts = ["html", "json"]
   page = ["html", "json"]

[params]
    github = "guylyons"
    linkedin = "guylyons"
    twitter = "yugsnoyl"
    author = "Guy Lyons"
    avatar = "/profile.png"
    contact = "mailto:website.guy@mailhero.io"
    subtitle = "just a dev named guy"

[[menu.main]]
    name = "About"
    url = "/about"
    weight = 3
# [[menu.main]]
#     name = "Illustration"
#     url = "/illustration"
#     weight = 1
# [[menu.main]]
#     name = "Resume"
#     url = "/resume"
#     weight = 1