baseURL = "https://yugsnoyl.com"
languageCode = "en-us"
title = "Recursive Fun"
theme = "pickles"

[params]
    twitter = "yugsnoyl"
    github = "guylyons"
    linkedin = "guylyons"
    # ga_api_key = "Your Google Analytics tracking id"
    author = "Guy Lyons"
    avatar = "/profile.png"
    # subtitle = ""
    contact = "mailto:website.guy@mailhero.io"