baseURL = "https://yugsnoyl.com/"
languageCode = "en-us"
title = "Guy Lyons"
theme = "noncomplex"
Paginate = 8 

[params]
    github = "guylyons"
    linkedin = "guylyons"
    twitter = "yugsnoyl"
    author = "Guy Lyons"
    avatar = "/profile.png"
    contact = "mailto:guylyons2@gmail.com"
    subtitle = "Developer • Illustrator"

[[menu.main]]
    # name = "Home"
    # url = "/"
[[menu.main]]
    # name = "Posts"
    # url = "/posts"
# [[menu.main]]
#     name = "About"
#     url = "/about"
    # weight = 1
