baseURL = "https://yugsnoyl.com/"
languageCode = "en-us"
title = "yug snoyl"
theme = "pickles"

[params]
    github = "guylyons"
    linkedin = "guylyons"
    twitter = "yugsnoyl"
    author = "Guy Lyons"
    avatar = "/profile.png"
    contact = "mailto:website.guy@mailhero.io"
    subtitle = "a blog about nothing"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about"
    weight = 2
[[menu.main]]
    name = "Illustration"
    url = "/illustration"
    weight = 3