baseURL = "https://yugsnoyl.com/"
languageCode = "en-us"
title = "Guy Lyons"
theme = "noncomplex-theme"
Paginate = 8 
pygmentsUseClasses=true

[params]
    github = "guylyons"
    linkedin = "guylyons"
    twitter = "yugsnoyl"
    author = "Guy Lyons"
    avatar = "/profile.png"
    contact = "mailto:guylyons2@gmail.com"
    subtitle = "Developer • Illustrator"

# [[menu.main]]
#     name = "Home"
#     url = "/"
#     weight = 1
# [[menu.main]]
#     name = "Posts"
#     url = "/posts"
#     weight = 2
# [[menu.main]]
#     name = "Tutorials"
#     url = "/tutorials"
# [[menu.main]]
#    name = "Art"
#    url = "/art"
#   weight = 3
