baseURL = "https://yugsnoyl.com"
languageCode = "en-us"
title = "Serenity Now"
theme = "pickles"

[params]
    github = "guylyons"
    linkedin = "guylyons"
    twitter = "yugsnoyl"
    # ga_api_key = "Your Google Analytics tracking id"
    author = "Guy Lyons"
    avatar = "/profile.png"
    subtitle = "Misadventures in Coding"
    contact = "mailto:website.guy@mailhero.io"