baseURL = "https://yugsnoyl.com/blog"
languageCode = "en-us"
title = "Incessant Barking"
theme = "pickles"

[params]
    twitter = "yugsnoyl"
    github = "guylyons"
    linkedin = "guylyons"
    ga_api_key = "Your Google Analytics tracking id"
    author = "Guy Lyons II"
    avatar = "/blog/profile.png"
    subtitle = "A Blog About Nothing"
    contact = "mailto:website.guy@mailhero.io"

# [[menu.main]]
#     name = "Home"
#     url = "/"
#     weight = 1

# [[menu.main]]
#     name = "About"
#     url = "/about"
#     weight = 2
