baseURL = "https://yugsnoyl.com"
languageCode = "en-us"
title = "Serenity Now"
theme = "pickles"

[params]
    twitter = "yugsnoyl"
    github = "guylyons"
    linkedin = "guylyons"
    ga_api_key = "Your Google Analytics tracking id"
    author = "Guy Lyons"
    avatar = "/profile.png"
    # subtitle = "A Blog About Nothing"
    contact = "mailto:website.guy@mailhero.io"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about"
    weight = 2
